### ISSUE TITLE
It's not working on a new patch.

### ISSUE THREAD

**Issue by remoshimei** [Owyn/auto-nego#10]

**Comment by remoshimei** [comment]
![frrgrtgrg](https://user-images.githubusercontent.com/65979078/89782608-4fa5f700-db1e-11ea-8453-772cc64e98e4.jpg)

**Comment by Owyn** [comment]
`unmapped packet` error doesn't not mean it is not working, it only means you don't have updated opcodes for it to work

**Comment by remoshimei** [comment]
I'm a girl and I don't know any of this. How can I do it?

**Comment by Owyn** [comment]
You're not supposed to.
You just wait till proxy devs give an update, or ask them for it.

**Comment by remoshimei** [comment]
You see there already was an update.
Your mod is the only mod not working after it.
You sure I need to wait more?
There almost a week passed.
Maybe it's you that need to fix something?

**Comment by Owyn** [comment]
No idea then. 🤷‍♀️

**Comment by remoshimei** [comment]
No negotiate mod out of all I found on github not working anymore(
